### ISSUE TITLE
FavouriteThis Use Case Presenter Bug

### ISSUE THREAD

**Issue by HC123abc** [HC123abc/Mindful-Meal-Planner-CSC207-Project-#22]
FavouriteThis Use case bug:
- Does not display the output data correctly
- When clicking the favorite button, nothing shows: should show a prompt saying favorite or unfavorite 
- Upon inspection: need to add a new attribute in CookThisOrReRoll state: favButtonPressed: bool
- propertychange checks this, then checks favorite and prompts correctly 

Problem Arises Branch: https://github.com/HC123abc/Mindful-Meal-Planner-CSC207-Project-/pull/19

**Comment by stwig** [comment]
Any updates on this? If this is done please close it.

**Comment by HC123abc** [comment]
I fixed it
